[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['cd backend && mvn clean package -DskipTests']

[phases.deploy]
cmds = ['cd backend && java -Dserver.port=$PORT -jar target/attendance-1.0.0.jar']

[start]
cmd = 'cd backend && java -Dserver.port=$PORT -jar target/attendance-1.0.0.jar'
